### PR TITLE
rems.application: tune layout of licenses

### LINKED ISSUE #1671: Long text licenses render badly

### PR DESCRIPTION
**Pull request by opqdonut**
in particular, fix expanded long text licenses

fixes #1671

# Definition of Done / Review checklist

## Reviewability
- [x] link to issue
- [x] consider adding screenshots for ease of review

### CODE REVIEW

**Comment by opqdonut** [comment]
Screenshot after change:

license-layout

**Comment by Macroz** [comment]
I think it would look better if the ok mark is next to the name of the license i.e. not centered vertically.

**Comment by opqdonut** [comment]
now it looks like this:
license-layout-2

**Comment by opqdonut** [comment]
better screenshot, with text expanded:
license-layout-3

**Comment by opqdonut** [comment]
now looks like this:
license-layout-4

**Pull request merged**
