### PR TITLE
test: try to make rems.test-browser/test-organizations more robust

### PR DESCRIPTION
**Pull request by opqdonut**

### CODE REVIEW

**Comment by opqdonut** [comment]
browser tests passed once

**Comment by opqdonut** [comment]
browser tests passed twice (on circle that is)

**Comment by opqdonut** [comment]
thrice

**Comment by opqdonut** [comment]
four times.

**Comment by opqdonut** [comment]
with these changes, test-organizations passes 8/8 times when running locally

without these changes, it passes 7/8 times

**Review by Macroz — APPROVED** [review]

**Pull request merged**
