### PR TITLE
Harmonize names

### PR DESCRIPTION
**Pull request by Macroz**
In a recent planning we discussed harmonizing the column names and the view/edit field names in the admin pages.

### CODE REVIEW

**Comment by aatkin** [comment]
should workflow and resource also have a column called title? at least form has a field called title, so i guess at least it should be harmonized? not sure about resource though

Screenshot 2022-04-01 at 16 16 17
Screenshot 2022-04-01 at 16 16 23

**Comment by Macroz** [comment]
> should form and resource also have a column called title? at least form has a field called title, so i guess at least it should be harmonized? not sure about resource though
> 
> Screenshot 2022-04-01 at 16 16 17 Screenshot 2022-04-01 at 16 16 23

The harmonization is that the column that is in the details is also on the table. For workflows there is no title so `Name` it is. For resources, `resid` is called `Resource` so that's what we have to use?

**Comment by aatkin** [comment]
> The harmonization is that the column that is in the details is also on the table. For workflows there is no title so `Name` it is. For resources, `resid` is called `Resource` so that's what we have to use?

I was talking about `Forms` here. Sorry for the confusion - the first message contained `workflow` but i typo'ed it there and had to edit it out.

**Comment by aatkin** [comment]
Looks like I was mistaken there - Form uses `name` as discussed and is thus harmonized already.

**Review by aatkin — APPROVED** [review]
:+1:

**Pull request merged**
