### PR TITLE
configure lein-cljfmt, fix most indentation errors it reports

### PR DESCRIPTION
**Pull request by opqdonut**

### CODE REVIEW

**Comment by opqdonut** [comment]
After this PR, `lein cljfmt` reports the following errors. Both are cases of `cljfmt` considering a function with the word `with` in the name to be macros.
```
src/clj/rems/application/search.clj has incorrect formatting
--- a/home/joel/work/csc/rems/src/clj/rems/application/search.clj
+++ b/home/joel/work/csc/rems/src/clj/rems/application/search.clj
@@ -135,7 +135,7 @@
   (when-let [query (parse-query query)]
     (refresh!) ; TODO: call from a background thread asynchronously?
     (with-searcher
-     (fn [^IndexSearcher searcher]
-       (->> (.search searcher query Integer/MAX_VALUE)
-            (get-application-ids searcher)
-            set)))))
+      (fn [^IndexSearcher searcher]
+        (->> (.search searcher query Integer/MAX_VALUE)
+             (get-application-ids searcher)
+             set)))))
test/clj/rems/db/test_entitlements.clj has incorrect formatting
--- a/home/joel/work/csc/rems/test/clj/rems/db/test_entitlements.clj
+++ b/home/joel/work/csc/rems/test/clj/rems/db/test_entitlements.clj
@@ -52,15 +52,15 @@
 
   (testing "ok :ga4gh action"
     (run-with-server
-      {:status 200}
-      (fn [server]
-        (is (nil? (#'entitlements/post-entitlements! {:action :ga4gh :entitlements +entitlements+})))
-        (is (= {:ga4gh_visa_v1 ["eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiQ29udHJvbGxlZEFjY2Vzc0dyYW50cyIsInZhbHVlIjoicmVzMSIsInNvdXJjZSI6Imh0dHBzOi8vZ2E0Z2gub3JnL2R1cmkvbm9fb3JnIiwiYnkiOiIiLCJhc3NlcnRlZCI6MTAwMjc1ODQwMDAwMH0.shOczQ78bE00HsvhPHqY1b5PcfIW2ebWd_4p6xb3TUg"
-                                "eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiQ29udHJvbGxlZEFjY2Vzc0dyYW50cyIsInZhbHVlIjoicmVzMiIsInNvdXJjZSI6Imh0dHBzOi8vZ2E0Z2gub3JnL2R1cmkvbm9fb3JnIiwiYnkiOiIiLCJhc3NlcnRlZCI6MTAzNDI5NDQwMDAwMH0.rfQTVmvlmkx2VsA5j5hGyaf0CUPh9I74WDlUbf_YHXk"]}
-               (-> (stub/recorded-requests server)
-                   first
-                   (get-in [:body "postData"])
-                   json/parse-string))))))
+     {:status 200}
+     (fn [server]
+       (is (nil? (#'entitlements/post-entitlements! {:action :ga4gh :entitlements +entitlements+})))
+       (is (= {:ga4gh_visa_v1 ["eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiQ29udHJvbGxlZEFjY2Vzc0dyYW50cyIsInZhbHVlIjoicmVzMSIsInNvdXJjZSI6Imh0dHBzOi8vZ2E0Z2gub3JnL2R1cmkvbm9fb3JnIiwiYnkiOiIiLCJhc3NlcnRlZCI6MTAwMjc1ODQwMDAwMH0.shOczQ78bE00HsvhPHqY1b5PcfIW2ebWd_4p6xb3TUg"
+                               "eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiQ29udHJvbGxlZEFjY2Vzc0dyYW50cyIsInZhbHVlIjoicmVzMiIsInNvdXJjZSI6Imh0dHBzOi8vZ2E0Z2gub3JnL2R1cmkvbm9fb3JnIiwiYnkiOiIiLCJhc3NlcnRlZCI6MTAzNDI5NDQwMDAwMH0.rfQTVmvlmkx2VsA5j5hGyaf0CUPh9I74WDlUbf_YHXk"]}
+              (-> (stub/recorded-requests server)
+                  first
+                  (get-in [:body "postData"])
+                  json/parse-string))))))
 
   (testing "not-found"
     (run-with-server

**Comment by opqdonut** [comment]
Hmm no, the test_entitlements.clj indentation that cljfmt proposed was correct. The one for search.clj is a bit weird but actually matches with what my emacs produces.

**Review by Macroz — APPROVED** [review]
I think this is a bit risky to do as there is a bunch of PRs so maybe rerun this fix after we get that stuff merged?

I didn't bother to check each line carefully. There is a surprisingly big number of changes.

As for `with-` that should be used only for the macros. If something is not a macro then it should be changed?

Subsequent blank lines improve readability between sections. I think it's a useful feature.

**Comment by opqdonut** [comment]
At first I was going to just make a PR with the configuration, and then later a cleanup PR. However all the fixes were in files that nobody is working on right now (as far as I can see) so I think this won't cause any conflicts.

**Review by marharyta — APPROVED** [review]

**Comment by marharyta** [comment]
Thanks a lot, @opqdonut

**Pull request merged**
