### PR TITLE
docs: add AVOID comments to code snippets in ADRs

### PR DESCRIPTION
**Pull request by opqdonut**

### CODE REVIEW

**Comment by opqdonut** [comment]
follow-up for #1760

**Comment by luontola** [comment]
For some of the big code samples it would be nice if the problematic line would be highlighted e.g. with a comment saying what to avoid.

**Comment by opqdonut** [comment]
Did you have something concrete in mind? I read through the examples and the text immediately prior to the AVOID snippets seemed to describe what to avoid pretty well.

**Comment by luontola** [comment]
I added my ideas as a commit.

**Comment by opqdonut** [comment]
good stuff :+1: (can't approve my own PR :)

**Pull request merged**
